### PR TITLE
Support For All Regions

### PR DESCRIPTION
**Pull request by leviferreira**
The idea here is to support for All regions

It changes the following behavior:
- Use config's section as region
  To add a new region just simply add a new section with it. e.g:

```
[eu-west-1]
access_key = <Your_Access_Key_Here>
secret_key = <Your_Secret_Key_Here>
```

It will not consider 'schedule' section as region.

Best Regards

### CODE REVIEW

**Comment by rwillians** [comment]
Works for me :+1:

**Comment by edsonlimadev** [comment]
Good idea 👍

**Comment by henriquefonseca** [comment]
Great!!!! ___

**Comment by leviferreira** [comment]
Any news?

**Pull request closed without merging**
